version: "3"

services:

  database:
    image: "postgres:10"
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
    networks:
      - omero
    volumes:
      - "database:/var/lib/postgresql/data"

  omeroserver:
    build: ./server
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      ROOTPASS: omero

      CONFIG_omero_client_icetransports: ssl,wss

      # Self-signed certificates are needed if you want to use secure
      # websocket proxying between nginx and omero (Nginx can't use ADH).
      # If you are connecting directly to OMERO.server wss this isn't
      # needed since the clients are configured to use ADH.
      CONFIG_omero_glacier2_IceSSL_Ciphers: ADH:HIGH
      CONFIG_omero_glacier2_IceSSL_DefaultDir: /etc/ssl/selfsigned
      CONFIG_omero_glacier2_IceSSL_CAs: server.pem
      CONFIG_omero_glacier2_IceSSL_CertFile: server.p12
      CONFIG_omero_glacier2_IceSSL_Password: secret

    networks:
      - omero
    ports:
      - "4064:4064"
      - "4066:4066"
    volumes:
      - "omero:/OMERO"
      - "./certs:/etc/ssl/selfsigned:ro${VOLOPTS-}"

  omeroweb:
    image: "openmicroscopy/omero-web-standalone:latest"
    environment:
      OMEROHOST: omeroserver
      CONFIG_omero_web__check_version: "false"
      CONFIG_omero_web_secure: "true"
    networks:
      - omero
    ports:
      - "4080:4080"

  nginx:
    image: library/nginx:1.14
    networks:
      - omero
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro${VOLOPTS-}"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro${VOLOPTS-}"
      - "./certs:/etc/nginx/ssl:ro${VOLOPTS-}"

networks:
  omero:

volumes:
  database:
  omero:
